### ISSUE TITLE
找不到合适 ABI 而无法安装

### ISSUE THREAD

**Issue by cornahere** [ArchiDreamZ/Living_With_SIster-Monochrome_Fantasy-Android-Chinese_localization#15]
Android 14 QPR2 后，原生系统删除了对 armabi-v7a 的支持，致使此后的 Android 因找不到合适 ABI 而无法安装。

**Comment by ArchiDreamZ** [comment]
![image](https://github.com/user-attachments/assets/8b917a2a-cfef-4ac8-ab9c-f0e62bb3bf3f)
你试试看我刚发布的这个调整过的版本还有这个问题嘛？

**Comment by cornahere** [comment]
感谢修复，修改后已经能够正常安装。
