### ISSUE TITLE
制作pc整合版的可能？

### ISSUE THREAD

**Issue by SSSoushi** [ArchiDreamZ/Living_With_SIster-Monochrome_Fantasy-Android-Chinese_localization#17]
大佬做的安卓整合版真的很好用（滑铲下跪膜拜
是否也能发布pc版呢（期待

**Comment by ArchiDreamZ** [comment]
PC不需要我做的，网络上有很多，再说了Steam版打补丁、打mod都很方便的。

**Comment by SSSoushi** [comment]
好吧，谢谢大佬

**Comment by webrsb** [comment]
感谢提供 [幽夜的优化版彩色包](https://github.com/ArchiDreamZ/Living_With_Sister-Monochrome_Fantasy-Android-Chinese_Localization/tree/YouYe_Color_ImagePack?tab=readme-ov-file) ，让 PC 玩家也可以使用优质彩色包。

我研究了好一阵子 UberWolf 才了解所谓删除 wolf 的细节
1. 启动 UberWolf，要先勾选 **选项** > **覆盖已提取文件**
   > 这步没做启动游戏会出现遗失档案的问题
2. 将游戏的 `Data` 文件夹里的所有 `*.wolf` 都用UberWolf解包
3. 再删除上一步被解包的所有 `*.wolf` 文件
4. 最后把仓库里的彩色包文件覆盖过去就完成了

**Comment by ArchiDreamZ** [comment]
@webrsb 勾选“Overwrite existing extracted data”这一项主要是有什么作用？
看字面意思的话，就是重新将所有.wolf文件重新解包一次吧。如果不勾选的话，是会直接跳过已解包过的文件吗？
这步没勾选就会“遗失档案”是什么意思？是遗失存档吗？这不应该吧，存档并不位于Data文件夹里，而是位于Save文件夹里。

**Comment by webrsb** [comment]
没有勾选“Overwrite existing extracted data”会跳过已经存在的资料夹，被 **skip**，如果再删除 **.wolf**，启动游戏会出现遗失档案的错误，跟存档无关，没处理好游戏启动就会异常了。

**Comment by ArchiDreamZ** [comment]
@webrsb 我明白了，指的是丢失游戏文件吧。
是海外华人吗？在大陆“档案”一般指存档哈哈
我会把这一步写进操作说明的，谢谢你的提醒！
