### ISSUE TITLE
关于覆盖安装巴图版作弊的问题

### ISSUE THREAD

**Issue by LweiH219** [ArchiDreamZ/Living_With_SIster-Monochrome_Fantasy-Android-Chinese_localization#3]
作者大大你好，感谢你的付出。
我尝试用巴图版覆盖安装最新6.11版来实现作弊，但是我发现安装看不到作弊入口的按钮，汉化回到了精翻之前，可以确定我是回退了，但是我看不到按钮。

**Comment by ArchiDreamZ** [comment]
右侧会出现很多按钮，右上角还有一个“全部回想”按钮。
如果没有那应该是你设备尺寸问题，按钮显示到外面去了。我也不知道该怎么办。

**Comment by umi-kotori520** [comment]
> 右侧会出现很多按钮，右上角还有一个“全部回想”按钮。 如果没有那应该是你设备尺寸问题，按钮显示到外面去了。我也不知道该怎么办。

我发现我手机未覆盖旧版反而有作弊按钮，到了覆盖版就没有作弊按钮了，很怪

**Comment by ArchiDreamZ** [comment]
现在我在原位上传了新的覆盖版，使用新的就有作弊按键了

**Comment by LweiH219** [comment]
感谢大佬，你还把巴图版的包里的冗余部分精简了，非常感谢。
